steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'production', '--project', '$PROJECT_ID', 
         '-q', '$_GAE_PROMOTE', '-v', '$_GAE_VERSION']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'staging', '--project', '$PROJECT_ID', 
         'set-traffic', '--splits', '$_GAE_TRAFFIC']